### PR TITLE
New methods for displaying progress, success, and error ProgressHUD

### PR DESCRIPTION
**Pull request by stefandeclerck**
This code may be a bit redundant but I have made this change to the ProgressHUD.m/h file every time I have used it. For some people who I've actually talked to at hackathons and recommended to use this, they ask me how to display a progressHUD without text. A lot of beginners don't understand that in order to not show any text in the progressHUD you have to set the value of the text parameter as `nil`. Most of them just put two empty quotation marks which of course ends up with the progressHUD view having added space at the bottom. I would like to propose to add this beginners method for all three types of progressHUD. I have implemented them as to be used as such in both objc and swift.

Objective-C

``` objective-c
[ProgressHUD show]
[ProgressHUD showSuccess]
[ProgressHUD showError]
```

Swift

``` swift
ProgressHUD.show()
ProgressHUD.showSuccess()
ProgressHUD.showError()
```

I think this would be better for beginners who are starting out with Swift or ObjC. Would love to see this pushed.

### CODE REVIEW

**Comment by relatedcode** [comment]
Good idea. Thanks! :)

**Comment by stefandeclerck** [comment]
Will this be merged?

**Comment by relatedcode** [comment]
Yes, but first I need to add the 'Interaction' version of these simplified methods as well...

**Comment by stefandeclerck** [comment]
👍

**Comment by glennposadas** [comment]
RIP, Stefan! I wondered why I couldn't find your branch, so I checked your profile, then checked your website, it didn't work. Then finally, googled you. Too young, gone too soon. 

https://www.lynchandsonsclawson.com/obituaries/obituary-listings?obId=1928251

**Pull request merged**
